### ISSUE TITLE
Bug: React key errors on the user settings page

### ISSUE THREAD

**Issue by nickytonline** [open-sauced/app#1988]
### Describe the bug

If you open the browser tools dev console on the user settings page, you see the following error multiple times.

```
client.js:1 Warning: Encountered two children with the same key, `GMT Standard Time`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
    at select
    at eval (webpack-internal:///./node_modules/@radix-ui/react-select/node_modules/@radix-ui/react-slot/dist/index.mjs:46:23)
    at eval (webpack-internal:///./node_modules/@radix-ui/react-select/node_modules/@radix-ui/react-slot/dist/index.mjs:20:23)
    at eval (webpack-internal:///./node_modules/@radix-ui/react-select/node_modules/@radix-ui/react-primitive/dist/index.mjs:44:26)
    at eval (webpack-internal:///./node_modules/@radix-ui/react-select/node_modules/@radix-ui/react-visually-hidden/dist/index.mjs:34:22)
    at eval (webpack-internal:///./node_modules/@radix-ui/react-select/dist/index.mjs:1201:20)
    at Provider (webpack-internal:///./node_modules/@radix-ui/react-select/node_modules/@radix-ui/react-context/dist/index.mjs:47:28)
    at Provider (webpack-internal:///./node_modules/@radix-ui/react-select/node_modules/@radix-ui/react-context/dist/index.mjs:47:28)
    at $cf1ac5d9fe0e8206$export$badac9ada3a0bdf9 (webpack-internal:///./node_modules/@radix-ui/react-select/node_modules/@radix-ui/react-popper/dist/index.mjs:63:28)
    at $cc7e05a45900e73f$export$ef9b1a59e592288f (webpack-internal:///./node_modules/@radix-ui/react-select/dist/index.mjs:133:28)
    at div
    at form
    at div
    at div
    at div
    at UserSettingsPage (webpack-internal:///./components/organisms/UserSettingsPage/user-settings-page.tsx:61:22)
    at div
    at ProfileSettings (webpack-internal:///./pages/user/settings.tsx:15:85)
    at main
    at div
    at div
    at ProfileLayout (webpack-internal:///./layouts/profile.tsx:14:26)
    at Provider (webpack-internal:///./node_modules/@radix-ui/react-context/dist/index.module.js:48:28)
    at $a093c7e1ec25a057$export$f78649fb9ca566b8 (webpack-internal:///./node_modules/@radix-ui/react-tooltip/dist/index.module.js:73:29)
    at PrivateWrapper (webpack-internal:///./layouts/private-wrapper.tsx:22:39)
    at PostHogProvider (webpack-internal:///./node_modules/posthog-js/react/dist/esm/index.js:21:23)
    at SessionContextProvider (webpack-internal:///./node_modules/@supabase/auth-helpers-react/dist/index.js:61:3)
    at SWRConfig (webpack-internal:///./node_modules/swr/_internal/dist/index.mjs:557:13)
    at MyApp (webpack-internal:///./pages/_app.tsx:93:27)
    at PathnameContextProviderAdapter (webpack-internal:///./node_modules/next/dist/shared/lib/router/adapters.js:113:26)
    at ErrorBoundary (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:306:63)
    at ReactDevOverlay (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:858:919)
    at Container (webpack-internal:///./node_modules/next/dist/client/index.js:110:27)
    at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:252:26)
    at Root (webpack-internal:///./node_modules/next/dist/client/index.js:452:27)
```

### Steps to reproduce

1. Make sure you're logged into https://app.opensauced.pizza.
2. Navigate to https://app.opensauced.pizza/user/settings.
3. Open the browser dev tools. Notice the repeating error about non-unique React keys.

![CleanShot 2023-10-23 at 16 53 41](https://github.com/open-sauced/app/assets/833231/146fc5ae-bdd8-42b6-82eb-94e0b014c433)

See [Lists and Keys](https://react.dev/learn/rendering-lists) in the React docs for more information about the `key` prop.

Look at the user settings component, https://github.com/open-sauced/app/blob/beta/components/organisms/UserSettingsPage/user-settings-page.tsx, specifically this piece of the JSX:

```jsx
<SelectContent position="item-aligned" className="bg-white">
  {timezones.map((timezone, index) => (
    <SelectItem key={`timezone_${index}`} value={timezone.value}>
      {timezone.text}
    </SelectItem>
  ))}
</SelectContent>
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by Satoshi-Sh** [comment]
I will work on this task. .take

**Comment by Satoshi-Sh** [comment]
![Screenshot from 2023-10-24 11-05-35](https://github.com/open-sauced/app/assets/73622805/43a2fd9a-0c19-448e-8d40-1a97537a9998)

The warning was kind of misleading. ```key={`timezone_${index}`}``` is fine as is. 
It came from the duplicated values in the timezone list.  If I added a space to the second one like  "GMT Standard Time ", the warning would not show up. 

Let me know what way you think is the best to fix this issue.

**Comment by nickytonline** [comment]
> ![Screenshot from 2023-10-24 11-05-35](https://user-images.githubusercontent.com/73622805/277736001-43a2fd9a-0c19-448e-8d40-1a97537a9998.png)
> 
> The warning was kind of misleading. `` key={`timezone_${index}`} `` is fine as is. It came from the duplicated values in the timezone list. If I added a space to the second one like "GMT Standard Time ", the warning would not show up.
> 
> Let me know what way you think is the best to fix this issue.

I wonder if that's an error. cc: @OgDev-01

**Comment by OgDev-01** [comment]
>  wonder if that's an error.

Not really an error, we just have to figure out something unique for the keys as it turns out the value isn't unique work

**Comment by nickytonline** [comment]
Ahh, wasn't sure if the timezone wasn't correct. In that case @Satoshi-Sh, the key can be a combo of the value and text to make it unique.

**Comment by OgDev-01** [comment]
> Let me know what way you think is the best to fix this issue


You can incorporate the index of the items to the key to keep them unique
