### ISSUE TITLE
Bug: Cannot read properties of undefined (reading 'split')

### ISSUE THREAD

**Issue by abhishekmmgn** [open-sauced/app#3865]
### Describe the bug

TypeError: Cannot read properties of undefined (reading 'split')
at $ (https://app.opensauced.pizza/_next/static/chunks/373-50ed224c6aeb8913.js:1:19184)
at ak (https://app.opensauced.pizza/_next/static/chunks/framework-314c182fa7e2bf37.js:9:60903)
at i (https://app.opensauced.pizza/_next/static/chunks/framework-314c182fa7e2bf37.js:9:119420)
at oD (https://app.opensauced.pizza/_next/static/chunks/framework-314c182fa7e2bf37.js:9:99073)
at https://app.opensauced.pizza/_next/static/chunks/framework-314c182fa7e2bf37.js:9:98940
at oO (https://app.opensauced.pizza/_next/static/chunks/framework-314c182fa7e2bf37.js:9:98947)
at oE (https://app.opensauced.pizza/_next/static/chunks/framework-314c182fa7e2bf37.js:9:95699)
at ox (https://app.opensauced.pizza/_next/static/chunks/framework-314c182fa7e2bf37.js:9:94254)
at x (https://app.opensauced.pizza/_next/static/chunks/framework-314c182fa7e2bf37.js:33:1364)
at MessagePort.T (https://app.opensauced.pizza/_next/static/chunks/framework-314c182fa7e2bf37.js:33:1894)
A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred

![image](https://github.com/user-attachments/assets/e059c5b4-21ba-4ffa-8b49-aa8b1a49cf10)

### Steps to reproduce

Go to https://app.opensauced.pizza/workspaces/[workspace-id]

**Comment by nickytonline** [comment]
Thanks for reporting @abhishekmmgn. I went to your workspace page, but the error does not seem to occur for me. Are you still experiencing the issue?

![CleanShot 2024-08-07 at 09 28 11](https://github.com/user-attachments/assets/67596275-af33-4e86-9bf2-8abad7fa1042)

**Comment by abhishekmmgn** [comment]
No, I've experienced it just after login.
The error was encountered in the third step of the onboarding process.

I checked again by creating another account and didn't experience it this time.

Thanks for checking it out @nickytonline .

**Comment by abhishekmmgn** [comment]
This is screenshot of console

![Screenshot from 2024-08-08 13-31-03](https://github.com/user-attachments/assets/eb2a1d62-6818-4de8-afbd-bc18ee38b6c5)

Here's the file and the line causing the error
![Screenshot from 2024-08-08 13-30-17](https://github.com/user-attachments/assets/93a7a313-2905-4ce4-94bc-f7566ca30b0d)

**Comment by abhishekmmgn** [comment]
Thanks for fixing it. @brandonroberts.
I wanted to ask, can I also contribute to open-sauced, If yes, is there any slack/discord channel for communication?
